# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [ ]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
arr = np.random.randint(0, 20, (4, 7))
arr

array([[ 9, 14, 19,  6,  5, 12,  7],
       [ 8,  6, 14, 11, 14, 19,  9],
       [ 1,  3,  6,  6,  0, 15, 19],
       [12,  6, 17, 12,  5,  4,  9]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
a = np.array([2,3,4])
print(type(a))
b = [2,3,4]
print(np.array(b))
print(np.arange(5))

<class 'numpy.ndarray'>
[2 3 4]
[0 1 2 3 4]


## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
print(np.loadtxt(r'C:\Users\Саня\Downloads\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
arr = np.loadtxt(r'C:\Users\Саня\Downloads\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)
print(f"2-й столбец: Среднее: {np.mean(arr[:, 1])}, Мин: {np.amin(arr[:, 1])}, Макс: {np.amax(arr[:, 1])}, Медиана: {np.median(arr[:, 1])}")
print(f"3-й столбец: Среднее: {np.mean(arr[:, 2])}, Мин: {np.amin(arr[:, 2])}, Макс: {np.amax(arr[:, 2])}, Медиана: {np.median(arr[:, 2])}")

2-й столбец: Среднее: 21601.00169, Мин: 0, Макс: 2147483647, Медиана: 40.0
3-й столбец: Среднее: 9.05528, Мин: 1, Макс: 39, Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
print(f"квантиль = {np.quantile(arr[:, 1], q=0.75)}")
print(arr[arr[:, 1]<65.0])

квантиль = 65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
from collections import Counter
#print(f"Продолжительность равная нулю: {Counter(arr[:, 1] == 0)[True]}")
m1 = arr2[:, 1] == 60
m2 = arr2[:, 2] == 16
m3 = m1*m2
print(np.count_nonzero(m3))
arr2 = arr.copy()
arr2[arr2[:, 1] == 0] += [0, 1, 0]

121


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(arr[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(len(np.unique(arr[:, 2])))
ag = np.unique(arr[:, 2], return_counts=True)
print(f"Значения: {ag[0]}\nКол-во: {ag[1]}")

37
Значения: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
Кол-во: [   13   926  2895  5515  7913  9376 10628 10951 10585  9591  8297  6605
  4997  3663  2595  1767  1246   790   573   376   217   161   105    69
    50    28    16    16    12    12     3     1     2     1     3     1
     1]


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
arr[arr[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
arr3 = arr.copy()
arr3 = np.c_[arr3, np.zeros(np.shape(arr)[0])]
arr3 = arr3.astype(float, copy=False)
arr3[:,3] += np.divide(arr3[:, 2], arr3[:, 1], out=arr3[:, 2], where=arr3[:, 1] != 0)
print(arr3)

[[1.27244000e+05 6.00000000e+01 2.66666667e-01 2.66666667e-01]
 [2.38910000e+04 2.50000000e+01 2.80000000e-01 2.80000000e-01]
 [9.47460000e+04 1.00000000e+01 6.00000000e-01 6.00000000e-01]
 ...
 [4.98432000e+05 6.50000000e+01 2.30769231e-01 2.30769231e-01]
 [3.70915000e+05 5.00000000e+00 8.00000000e-01 8.00000000e-01]
 [8.19930000e+04 1.40000000e+02 1.00000000e-01 1.00000000e-01]]


In [ ]:
np.amax(arr3[:,3])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
arr_sort = arr[arr[:, 1].argsort()] # sort arr
arr_sort_100 = np.flipud(arr_sort) #reverse
print(np.sum(arr_sort_100[:100, :], axis=0)[2]/100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
ind = np.random.randint(100000, size=10)
print(ind)
print(arr[ind, :])

[28509 69582 85483 48287  4406 98451 10856 20905 49660 40635]
[[324444     50     11]
 [ 76983     35      5]
 [361683     50     15]
 [ 27033    105     10]
 [ 99817     10      8]
 [  7086      5      8]
 [167746    205     16]
 [180645     15      7]
 [ 62665     25      9]
 [363874     35     14]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
print(np.sum(arr, axis=0)[2]/arr.shape[0]) # среднее значение
print(np.sum(arr[:, 2] < np.mean(arr[:,2]))/arr.shape[0]*100)

9.05528
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
arr_simple = arr.copy()
arr_simple = np.c_[arr_simple, np.zeros(np.shape(arr)[0], dtype='int64')] # соединяет два массива вдоль ОY
arr_simple[np.logical_and((arr_simple[:, 1] <= 20), (arr_simple[:, 2] <= 5))] += [0, 0, 0, 1]
print(*arr_simple, sep='\n')

13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(np.sum(arr_simple, axis=0)[3]/arr_simple.shape[0]*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
#первый элемент на оси ноль - группа 0
#второй элемент на оси ноль - группа 1
#третий элемент на оси ноль - группа 2
arr_axis_0_gp_1 = arr[arr[:, 1] < 10]
print(arr_axis_0_gp_1.shape)
arr_axis_0_gp_2 = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
print(arr_axis_0_gp_2.shape)
arr_axis_0_gp_3 = arr[arr[:, 1] > 20]
print(arr_axis_0_gp_3.shape)
print()
arr_3D = np.stack((arr_axis_0_gp_1, arr_axis_0_gp_2[:7588], arr_axis_0_gp_3[:7588]))
print(arr_3D.shape)
print()
print(arr_3D)

(7588, 3)
(12661, 3)
(73350, 3)

(3, 7588, 3)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [ 24549     70      6]
  [449468     50     11]
  [ 28830     65     13]]]
